### ISSUE TITLE
Übersetzungdatei in .md

### ISSUE THREAD

**Issue by mikewuerfel** [Bobby-Git/Gloomhaven-German-Translation#2]
Hallo Bobby,

Du hast die Übersetzungdatei in .md Format im Repo bereitgestellt. Hat dies einen besonderen Grund? Im Original ist dies eine CSV-Datei. Ich empfehle, dass Du diese auch in diesem Format bereitstellst. Das bearbeiten ist dann leichter.

Kannst Du noch die CSV-Datei für uns bereitstellen?

Gruß
Reo

**Comment by Bobby-Git** [comment]
Hi Reo,

die .csv ist jetzt online. 

Danke nochmal
Gruß
Bobby

**Comment by mikewuerfel** [comment]
Perfekt. Vielen Dank.
